language: java

script: ./bin/run_tests.sh

before_install: ./bin/install_common.sh

notifications:
  email:
    recipients:
      - greenbutton-dev@googlegroups.com
    on_success: always

branches:
  only:
    - master